# MJERENJE USPJEŠNOSTI INVESTICIJSKIH FONDOVA

```{r}
source_eval <- function(file) source(file, print.eval = TRUE)
source_eval('uncommon.r')
```


## Ekstrakcija i normalizacija podataka

```{r}
source('data_extraction.r')
xs <- read_normalize(CSV_DATA)
```

### Podjela prema tipovima fondova
```{r}
investment_funds <- c("ERSTEAdriaticEquity", "OTPMeridian20", "ZBAktiv")
pension_funds <- c("RaiffeisenDMF", "ERSTEPlaviEXPERT", "ERSTEPlaviPROTECT")
market_portfolio <- c("CROBEX")

xs.market_portfolio <- to_data_frame(xs, market_portfolio, xs.market_portfolio)
xs.investment <- to_data_frame(xs, investment_funds, xs.investment)
xs.pension <- to_data_frame(xs, pension_funds, xs.pension)

data_columns <- c(pension_funds, investment_funds, market_portfolio)
xs.funds <- xs[, data_columns]
```

### Povrati
```{r}
diff_function_log <- function(St, St_minus_one) log(St) - log(St_minus_one)
xs.log_returns <- to_time_series_diff_df(xs, data_columns, diff_function_log)

diff_function_sub <- function(St, St_minus_one) St - St_minus_one
xs.returns <- to_time_series_diff_df(xs, data_columns, diff_function_sub)
```

### Sažeci
```{r}
xs.summary <- summary(xs.funds)
xs.returns.summary <- summary(xs.returns[data_columns])
xs.log_returns.summary <- summary(xs.log_returns[data_columns])

df_summary <- function(summary) data.frame(unclass(summary), check.names = FALSE, stringsAsFactors = FALSE)

df_summary(xs.summary)
df_summary(xs.returns.summary)
df_summary(xs.log_returns.summary)
```
## Mjere raspršenosti
```{r}

apply(xs.funds,2,var,na.rm=T) 
apply(xs.funds,2,sd,na.rm=T) 

```

## Grafički prikaz podataka
```{r}
source('plotting.r')
require(reshape2)

ggplot(xs, aes(Date, CROBEX)) + 
  geom_line()

df <- melt(xs[c("Date", investment_funds, pension_funds)], 
           id.vars = 'Date', 
           variable.name = 'Fondovi')
ggplot(df, aes(Date, value)) + geom_line(aes(colour = Fondovi))


df.returns <- melt(xs.returns[c("Date", investment_funds, pension_funds)], 
                   id.vars = 'Date', 
                   variable.name = 'Fondovi')
```

```{r}
ggplot(df.returns, aes(Date, value)) + geom_boxplot(aes(Fondovi)) + ylim(c(-10, 10))

#plot_timeseries(xs, xs$Date, xs$CROBEX)
#xs.graphs.timeseries <- mapply( function(data_col, name) plot_timeseries(xs, xs$Date, data_col, name), xs.funds, colnames(xs.funds) )
#class(xs.graphs.timeseries)
#xs.graphs.boxplots <- boxplot(xs[get_data_cols_without_market_portfolio(xs)])
#xs.log_returns.graphs.boxplots <- boxplot(xs.log_returns[get_data_cols_without_market_portfolio(xs.log_returns)], ylim = c(-0.1, 0.1) )
```

## Testovi povrata investicijskih fondova u odnosu na CROBEX
```{r}
lapply(xs.returns[investment_funds], function(r) t.test(xs.returns$CROBEX, r))
```

## Testovi povrata mirovinskih fondova u odnosu na CROBEX
```{r}
require(quantmod)
lapply(xs.returns[pension_funds], function(r) t.test(xs.returns$CROBEX, r))
```


## CAPM model

```{r}
dates <- xs.returns$Date

year <- function(date) format(date, "%Y")
get_for_year <- function(df, dates, desired_year) df[year(dates) == desired_year, ]

xs.2010 <- get_for_year(xs.returns, xs.returns$Date, 2010)

zbaktiv.2010 <- xs.2010$ZBAktiv #xs.2010[c('Date', 'ZBAktiv')]
capm.market.2010 <- xs.2010$CROBEX #xs.2010[c('Date', 'CROBEX')]
capm.risk_free.2010 <- xs.2010$InterestRate #[c('Date', 'InterestRate')]

lm(formula = zbaktiv.2010 ~ (capm.market.2010 - capm.risk_free.2010))
```

# CAPM model 2
```{r}
require(PerformanceAnalytics)
library(xts)

#zbaktiv.ts <- xts(zbaktiv.2010[, -1], order.by=zbaktiv.2010$Date)
#capm.m.ts <-  xts(capm.market.2010[, -1], order.by=capm.market.2010$Date)
#capm.rf.2010 <- xts(capm.risk_free.2010[, -1], order.by=capm.risk_free.2010$Date) 

CAPM.beta(zbaktiv.ts, capm.m.ts, capm.rf.2010)

qqnorm(xs.returns$ZBAktiv)
qqline(xs.returns$ZBAktiv)

qqnorm(apply.weekly(xts(xs.returns$ZBAktiv, order.by = xs.returns$Date), mean))
qqline(apply.weekly(xts(xs.returns$ZBAktiv, order.by = xs.returns$Date), mean))

```
















